# Early Detection of Chronic Kidney Disease Using Machine Learning Techniques

## Data Pre-Processing

In [1]:
# importing all the necessary libraries and classes

import pandas as pd

In [2]:
df= pd.read_csv('kidney_disease_dataset_cleaned.csv')
df.head()

,age,bloodPressure,specificGravity,albumin,sugar,redBloodCells,pusCells,pusCellClumps,bacteria,bloodGlucoseRandom,...,packedCellVolume,whiteBloodCellCount,redBloodCellCount,hypertension,diabetesMellitus,coronaryArteryDisease,appetite,pedalEdema,anemia,class
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44.0,7800.0,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd

In [4]:
#checking for null values in the dataset
df.isnull().sum().sort_values()

class                      0
pedalEdema                 1
appetite                   1
anemia                     1
coronaryArteryDisease      2
diabetesMellitus           2
hypertension               2
pusCellClumps              4
bacteria                   4
age                        9
bloodPressure             12
serumCreatinine           17
bloodUrea                 19
bloodGlucoseRandom        44
albumin                   46
specificGravity           47
sugar                     49
haemoglobin               52
pusCells                  65
packedCellVolume          71
sodium                    87
potassium                 88
whiteBloodCellCount      106
redBloodCellCount        131
redBloodCells            152
dtype: int64

In [5]:
# Extracting categorical and numerical columns

categorical_cols = [col for col in df.columns if df[col].dtype == 'object']
numerical_cols = [col for col in df.columns if df[col].dtype != 'object']

In [ ]:
df[]